name: Generate Commit Graph

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily

jobs:
  graph:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pygithub

      - name: Generate commit graph
        env:
          CUSTOM_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          python repograph.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add repograph.svg
          git commit -m "Update repo graph"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}